#
# Hugo configuration file
#
baseURL: https://link.seisman.info/
languageCode: en-us
title: SeisLinks
copyright: "[Unlicense](https://unlicense.org/), 2018 - {year}."

disableKinds:
- taxonomyTerm
- RSS
enableGitInfo: true

params:
  lastupdate: Built by [Hugo](https://gohugo.io/) on {now}.
              Source codes available on [GitHub](https://github.com/seisman/link.seisman.info).

  assets:
    bootstrap_cdn: https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap
    bootstrap_version: 4.5.2

    bootswatch_cdn: https://cdnjs.cloudflare.com/ajax/libs/bootswatch
    bootswatch_version: 4.5.2
    bootswatch_theme: cosmo

    fontawesome_cdn: https://cdnjs.cloudflare.com/ajax/libs/font-awesome
    fontawesome_version: 5.15.1

    jquery_cdn: https://cdnjs.cloudflare.com/ajax/libs/jquery
    jquery_version: 3.5.1

  edit_page:
    repo_url: https://github.com/seisman/link.seisman.info
    edit_mode: edit
    repo_dir: content
    edit_text: Contribute more links to this page!
